FROM golang:1.23 as builder

WORKDIR /app
COPY go.mod go.sum ./
RUN go mod download
COPY . .
RUN CGO_ENABLED=0 GOOS=linux go build -o scanner ./cmd/scanner

FROM gcr.io/distroless/base-debian11
WORKDIR /app
COPY --from=builder /app/scanner .
USER nonroot:nonroot
ENTRYPOINT ["./scanner"]
