FROM golang:1.23 AS builder

WORKDIR /app
COPY go.mod go.sum ./
RUN go mod download
COPY . .
RUN CGO_ENABLED=0 GOOS=linux go build -o api-gateway ./cmd/api

FROM gcr.io/distroless/base-debian11
WORKDIR /app
COPY --from=builder /app/api-gateway .
USER nonroot:nonroot
ENTRYPOINT ["./api-gateway"]
