FROM golang:1.23 as builder

WORKDIR /app
COPY go.mod go.sum ./
RUN go mod download
COPY . .
RUN CGO_ENABLED=0 GOOS=linux go build -o orchestrator ./cmd/orchestrator

FROM gcr.io/distroless/base-debian11
WORKDIR /app
COPY --from=builder /app/orchestrator .
USER nonroot:nonroot
ENTRYPOINT ["./orchestrator"]
