FROM golang:1.24 AS builder

WORKDIR /app
COPY go.mod go.sum ./
RUN go mod download
COPY . .
RUN CGO_ENABLED=0 GOOS=linux go build -o client-api ./cmd/api

FROM gcr.io/distroless/base-debian11
WORKDIR /app
COPY --from=builder /app/client-api .
USER nonroot:nonroot
ENTRYPOINT ["./client-api"]
