apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: client-http-ingress
  namespace: secret-scanner
  labels:
    app: client-api
    component: api
  annotations:
    konghq.com/strip-path: "true"
    konghq.com/preserve-host: "true"
    # Support for larger request bodies (same as previous nginx config)
    konghq.com/request-size-limit: "50m"
spec:
  ingressClassName: kong
  rules:
  - host: api.local.gitleaks.armada
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: client-api-svc
            port:
              number: 80
