apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: client-http-ingress
  namespace: secret-scanner
  labels:
    app: client-api
    component: api
  annotations:
    nginx.ingress.kubernetes.io/proxy-body-size: "50m"
    nginx.ingress.kubernetes.io/ssl-redirect: "false"
spec:
  ingressClassName: nginx
  rules:
  - host: api.local.gitleaks.armada
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: client-api-svc
            port:
              number: 80
