apiVersion: v1
kind: ConfigMap
metadata:
  name: scanner-config
  namespace: secret-scanner
data:
  KAFKA_TASK_CREATED_TOPIC: "task-created"
  KAFKA_JOB_CREATED_TOPIC: "job-created"
  KAFKA_SCANNING_TASK_TOPIC: "scanning-tasks"
  KAFKA_HIGH_PRIORITY_TASK_TOPIC: "high-priority-tasks"
  KAFKA_JOB_METRICS_TOPIC: "job-metrics"
  KAFKA_RESULTS_TOPIC: "results"
  KAFKA_PROGRESS_TOPIC: "progress"
  KAFKA_RULES_REQUEST_TOPIC: "rules-requests"
  KAFKA_RULES_RESPONSE_TOPIC: "rules-responses"
  KAFKA_BROKERS: "kafka:9092"
  POSTGRES_HOST: "postgres"
  POSTGRES_PORT: "5432"
  POSTGRES_DB: "secretscanner"
  POSTGRES_USER: "postgres"
  OTEL_EXPORTER_OTLP_ENDPOINT: "otel-collector.secret-scanner.svc.cluster.local:4317"
  OTEL_SAMPLING_RATIO: "0.6"
