apiVersion: apps/v1
kind: Deployment
metadata:
  name: scanner-controller
spec:
  replicas: 3
  selector:
    matchLabels:
      app: scanner-controller
  template:
    metadata:
      labels:
        app: scanner-controller
    spec:
      serviceAccountName: secret-scanner-sa
      containers:
      - name: controller
        image: controller:latest
        imagePullPolicy: IfNotPresent
        resources:
          requests:
            memory: "256Mi"
            cpu: "200m"
          limits:
            memory: "512Mi"
            cpu: "400m"
        env:
        - name: POD_NAME
          valueFrom:
            fieldRef:
              fieldPath: metadata.name
        - name: POD_NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
        - name: KAFKA_BROKERS
          value: "kafka:9092"
        - name: KAFKA_TASK_TOPIC
          value: "scanner-tasks"
        - name: KAFKA_RESULTS_TOPIC
          value: "scanner-results"
        - name: KAFKA_GROUP_ID
          value: "controller-group"
        volumeMounts:
        - name: scanner-config
          mountPath: /etc/scanner/config
          readOnly: true
      volumes:
      - name: scanner-config
        secret:
          secretName: scanner-targets
