apiVersion: v1
kind: ServiceAccount
metadata:
  name: secret-scanner-sa
  namespace: default
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: scanner-controller-role
  namespace: default
rules:
- apiGroups: [""]
  resources: ["pods"]
  verbs: ["get", "list", "watch"]
- apiGroups: ["coordination.k8s.io"]
  resources: ["leases"]
  verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: scanner-controller-binding
  namespace: default
subjects:
- kind: ServiceAccount
  name: secret-scanner-sa
  namespace: default
roleRef:
  kind: Role
  name: scanner-controller-role
  apiGroup: rbac.authorization.k8s.io
