apiVersion: v1
kind: ServiceAccount
metadata:
  name: secret-scanner-sa
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: secret-scanner-role
rules:
- apiGroups: ["coordination.k8s.io"]
  resources: ["leases"]
  verbs: ["create", "get", "update", "list"]
- apiGroups: [""]
  resources: ["pods"]
  verbs: ["get", "list", "watch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: secret-scanner-role-binding
subjects:
- kind: ServiceAccount
  name: secret-scanner-sa
roleRef:
  kind: Role
  name: secret-scanner-role
  apiGroup: rbac.authorization.k8s.io
