apiVersion: apps/v1
kind: Deployment
metadata:
  name: scanner-worker
spec:
  replicas: 2
  selector:
    matchLabels:
      app: scanner-worker
  template:
    metadata:
      labels:
        app: scanner-worker
    spec:
      containers:
      - name: scanner
        image: scanner:latest
        imagePullPolicy: IfNotPresent
        resources:
          requests:
            memory: "256Mi"
            cpu: "200m"
          limits:
            memory: "512Mi"
            cpu: "400m"
        env:
        - name: POD_NAME
          valueFrom:
            fieldRef:
              fieldPath: metadata.name
        - name: KAFKA_BROKERS
          value: "kafka:9092"
        - name: KAFKA_TASK_TOPIC
          value: "scanner-tasks"
        - name: KAFKA_RESULTS_TOPIC
          value: "scanner-results"
        - name: KAFKA_GROUP_ID
          value: "scanner-workers"
