apiVersion: v1
kind: ConfigMap
metadata:
  name: tempo-config
  namespace: secret-scanner
data:
  tempo.yaml: |
    usage_report:
      reporting_enabled: false

    server:
      http_listen_port: 3200

    distributor:
      receivers:
        otlp:
          protocols:
            http:
            grpc:

    ingester:
      trace_idle_period: 10s
      max_block_bytes: 1_000_000
      max_block_duration: 5m

    compactor:
      compaction:
        compaction_window: 1h
        max_block_bytes: 100_000_000
        block_retention: 1h
        compacted_block_retention: 10m

    storage:
      trace:
        backend: local
        block:
          bloom_filter_false_positive: .05
          v2_index_downsample_bytes: 1000
          v2_encoding: zstd
        wal:
          path: /tmp/tempo/wal
          v2_encoding: snappy
        local:
          path: /tmp/tempo/blocks
        pool:
          max_workers: 100
          queue_depth: 10000

    overrides:
      metrics_generator_processors: [service-graphs, span-metrics]
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: tempo
  namespace: secret-scanner
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: tempo
  template:
    metadata:
      labels:
        app: tempo
    spec:
      containers:
      - name: tempo
        image: grafana/tempo:2.6.0
        args:
        - -config.file=/tempo-conf/tempo.yaml
        ports:
        - containerPort: 3200
          name: http
        - containerPort: 4317
          name: otlp-grpc
        - containerPort: 4318
          name: otlp-http
        volumeMounts:
        - name: config-volume
          mountPath: /tempo-conf
        resources:
          requests:
            cpu: 100m
          limits:
            cpu: 1000m
      volumes:
      - name: config-volume
        configMap:
          name: tempo-config
---
apiVersion: v1
kind: Service
metadata:
  name: tempo
  namespace: secret-scanner
spec:
  type: ClusterIP
  selector:
    app: tempo
  ports:
  - port: 3200
    name: http
  - port: 4317
    name: otlp-grpc
  - port: 4318
    name: otlp-http
