openapi: '3.0.3'
info:
  title: API Specification for Gitleaks Armada
  version: '1.0'
servers:
  - url: https://api.server.test/v1 # TODO: change to the actual URL
paths:
  /v1/scan:
    post:
      summary: Start a new scan operation
      operationId: startScan
      tags:
        - Scanning
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/ScanRequest'
      responses:
        '202':
          description: Scan started request accepted
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ScanResponse'
        '400':
          description: Invalid request parameters
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
        '500':
          description: Internal server error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
components:
  schemas:
    ScanRequest:
      type: object
      required:
        - name
        - source_type
      properties:
        name:
          type: string
          description: Unique identifier for the scan operation
        source_type:
          type: string
          enum: [github, s3, url]
          description: Type of source to scan
        source_auth:
          $ref: '#/components/schemas/SourceAuth'
        github:
          $ref: '#/components/schemas/GitHubConfig'
        s3:
          $ref: '#/components/schemas/S3Config'
        url:
          $ref: '#/components/schemas/URLConfig'
        metadata:
          type: object
          additionalProperties:
            type: string
          description: Additional metadata for the scan

    RetryConfig:
      type: object
      properties:
        max_attempts:
          type: integer
          description: Maximum number of retry attempts
        initial_wait:
          type: string
          format: duration
          description: Initial wait time between retries
        max_wait:
          type: string
          format: duration
          description: Maximum wait time between retries

    ScanResponse:
      type: object
      required:
        - id
        - status
      properties:
        id:
          type: string
          format: uuid
          description: Unique identifier for the scan job
          example: "123e4567-e89b-12d3-a456-426614174000"
        status:
          type: string
          enum: [queued]
          description: Current status of the scan job
          example: "queued"
      example:
        id: "123e4567-e89b-12d3-a456-426614174000"
        status: "queued"

    ErrorResponse:
      type: object
      required:
        - code
        - message
      properties:
        code:
          type: string
          enum:
            - invalid_argument
            - internal
          description: Error code identifying the type of error
        message:
          type: string
          description: Human-readable error message

    SourceAuth:
      type: object
      description: Authentication configuration for the source
      required:
        - type
      properties:
        type:
          type: string
          enum: [none, basic, token, oauth, aws]
          description: Type of authentication
          example: "token"
        credentials:
          type: object
          additionalProperties: true
          description: Authentication credentials specific to the auth type

    GitHubConfig:
      type: object
      required:
        - repository_urls
      properties:
        repository_urls:
          type: array
          items:
            type: string
            format: uri
            pattern: '^https://github\.com/[^/]+/[^/]+$'
          description: List of GitHub repository URLs (e.g., https://github.com/owner/repo)
          example: ["https://github.com/trufflesecurity/trufflehog"]
          minItems: 1

    S3Config:
      type: object
      required:
        - bucket
        - region
      properties:
        bucket:
          type: string
          description: S3 bucket name
        prefix:
          type: string
          description: S3 bucket prefix
        region:
          type: string
          description: S3 bucket region

    URLConfig:
      type: object
      required:
        - urls
      properties:
        urls:
          type: array
          items:
            type: string
            format: uri
          description: List of URLs to scan
          minItems: 1
        archive_format:
          type: string
          enum: [none, gzip, tar.gz, zip, warc.gz, auto]
          default: none
        rate_limit:
          type: number
          format: float
          minimum: 0
        headers:
          type: object
          additionalProperties:
            type: string
